# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.25)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS libssh2::libssh2_static libssh2::libssh2_shared)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target libssh2::libssh2_static
add_library(libssh2::libssh2_static STATIC IMPORTED)

set_target_properties(libssh2::libssh2_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/git/github/windows/tools/scanner/src/lib/libssh2/include"
  INTERFACE_LINK_LIBRARIES "\$<\$<NOT:\$<CONFIG:DEBUG>>:C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib>;\$<\$<CONFIG:DEBUG>:C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib>;\$<\$<NOT:\$<CONFIG:DEBUG>>:C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib>;\$<\$<CONFIG:DEBUG>:C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib>;\$<LINK_ONLY:crypt32>;\$<LINK_ONLY:bcrypt>;\$<LINK_ONLY:ws2_32>"
)

# Create imported target libssh2::libssh2_shared
add_library(libssh2::libssh2_shared SHARED IMPORTED)

set_target_properties(libssh2::libssh2_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/git/github/windows/tools/scanner/src/lib/libssh2/include"
)

# Import target "libssh2::libssh2_static" for configuration "Debug"
set_property(TARGET libssh2::libssh2_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(libssh2::libssh2_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "D:/git/github/windows/tools/scanner/src/libssh2/src/Debug/libssh2_static.lib"
  )

# Import target "libssh2::libssh2_shared" for configuration "Debug"
set_property(TARGET libssh2::libssh2_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(libssh2::libssh2_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/git/github/windows/tools/scanner/src/libssh2/src/Debug/libssh2.lib"
  IMPORTED_LOCATION_DEBUG "D:/git/github/windows/tools/scanner/src/libssh2/src/Debug/libssh2.dll"
  )

# Import target "libssh2::libssh2_static" for configuration "Release"
set_property(TARGET libssh2::libssh2_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libssh2::libssh2_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "D:/git/github/windows/tools/scanner/src/libssh2/src/Release/libssh2_static.lib"
  )

# Import target "libssh2::libssh2_shared" for configuration "Release"
set_property(TARGET libssh2::libssh2_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libssh2::libssh2_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/git/github/windows/tools/scanner/src/libssh2/src/Release/libssh2.lib"
  IMPORTED_LOCATION_RELEASE "D:/git/github/windows/tools/scanner/src/libssh2/src/Release/libssh2.dll"
  )

# Import target "libssh2::libssh2_static" for configuration "MinSizeRel"
set_property(TARGET libssh2::libssh2_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(libssh2::libssh2_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "D:/git/github/windows/tools/scanner/src/libssh2/src/MinSizeRel/libssh2_static.lib"
  )

# Import target "libssh2::libssh2_shared" for configuration "MinSizeRel"
set_property(TARGET libssh2::libssh2_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(libssh2::libssh2_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/git/github/windows/tools/scanner/src/libssh2/src/MinSizeRel/libssh2.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/git/github/windows/tools/scanner/src/libssh2/src/MinSizeRel/libssh2.dll"
  )

# Import target "libssh2::libssh2_static" for configuration "RelWithDebInfo"
set_property(TARGET libssh2::libssh2_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(libssh2::libssh2_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/git/github/windows/tools/scanner/src/libssh2/src/RelWithDebInfo/libssh2_static.lib"
  )

# Import target "libssh2::libssh2_shared" for configuration "RelWithDebInfo"
set_property(TARGET libssh2::libssh2_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(libssh2::libssh2_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/git/github/windows/tools/scanner/src/libssh2/src/RelWithDebInfo/libssh2.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/git/github/windows/tools/scanner/src/libssh2/src/RelWithDebInfo/libssh2.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
